# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning Lab
email: molly.josephs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/learning-lab" # the subpath of your site, e.g. /blog
url: "mojopi.github.io/learning-lab" # the base hostname & protocol for your site
revealurl: "https://mojopi.github.io/learning-lab/reveal"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown

collections:
  portfolio-eighth:
    output: true
    permalink: /:collection/:name/
  code:
    output: true
  portfolio-seventh:
    output: true
    permalink: /:collection/:name/
  code:
    output: true